name: Test and Publish Python Package

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install gdal
        run: sudo apt-get install -y gdal-bin libgdal-dev

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]
      - name: isort
        if: always()
        run: isort --check-only .
      - name: black
        if: always()
        run: black . --check
  deploy:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [lint]

    runs-on: ubuntu-latest

    name: Upload release to PyPI
    environment:
      name: release
      url: https://pypi.org/p/vectors2vrt
    permissions:
      id-token: write 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3      
      with:
        python-version: '3.x'
    - name: Install gdal
      run: sudo apt-get install -y gdal-bin libgdal-dev  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build --sdist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
